import type { Product, Order, User, AuditLog, MouvementStock } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    nom: 'Diallo',
    prenom: 'Mamadou',
    email: 'admin@jadore.sn',
    role: 'admin',
    actif: true,
    dateCreation: '2024-01-10T08:00:00Z',
    derniereConnexion: '2026-05-17T07:45:00Z',
    telephone: '+221 77 100 00 01',
  },
  {
    id: 'u2',
    nom: 'Ndiaye',
    prenom: 'Fatou',
    email: 'stock@jadore.sn',
    role: 'stock',
    actif: true,
    dateCreation: '2024-02-01T08:00:00Z',
    derniereConnexion: '2026-05-16T16:30:00Z',
    telephone: '+221 76 200 00 02',
  },
  {
    id: 'u3',
    nom: 'Sow',
    prenom: 'Ibrahima',
    email: 'vendeur1@jadore.sn',
    role: 'vendeur',
    actif: true,
    dateCreation: '2024-03-15T08:00:00Z',
    derniereConnexion: '2026-05-17T09:10:00Z',
    telephone: '+221 70 300 00 03',
  },
  {
    id: 'u4',
    nom: 'Fall',
    prenom: 'Aissatou',
    email: 'vendeur2@jadore.sn',
    role: 'vendeur',
    actif: true,
    dateCreation: '2024-04-01T08:00:00Z',
    derniereConnexion: '2026-05-15T14:20:00Z',
    telephone: '+221 78 400 00 04',
  },
  {
    id: 'u5',
    nom: 'Mbaye',
    prenom: 'Cheikh',
    email: 'stock2@jadore.sn',
    role: 'stock',
    actif: false,
    dateCreation: '2024-05-01T08:00:00Z',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    nom: "Huile J'adore 1L",
    categorie: 'huile',
    prix: 1500,
    quantite: 240,
    seuilAlerte: 50,
    unite: 'bouteilles',
    image: '/images/Huile.jpg',
  },
  {
    id: 'p2',
    nom: "Huile J'adore 5L",
    categorie: 'huile',
    prix: 6500,
    quantite: 30,
    seuilAlerte: 40,
    unite: 'bidons',
    image: '/images/Huile2.jpg',
  },
  {
    id: 'p3',
    nom: "Riz J'adore 25kg",
    categorie: 'riz',
    prix: 18000,
    quantite: 85,
    seuilAlerte: 20,
    unite: 'sacs',
    image: '/images/Riz.jpg',
  },
  {
    id: 'p4',
    nom: "Riz J'adore 5kg",
    categorie: 'riz',
    prix: 3800,
    quantite: 120,
    seuilAlerte: 30,
    unite: 'sachets',
    image: '/images/Riz.jpg',
  },
  {
    id: 'p5',
    nom: "Sucre J'adore 1kg",
    categorie: 'sucre',
    prix: 750,
    quantite: 350,
    seuilAlerte: 80,
    unite: 'sachets',
    image: '/images/Sucre.jpeg',
  },
  {
    id: 'p6',
    nom: "Sucre J'adore 5kg",
    categorie: 'sucre',
    prix: 3500,
    quantite: 18,
    seuilAlerte: 25,
    unite: 'sachets',
    image: '/images/Sucre2.jpeg',
  },
  {
    id: 'p7',
    nom: "Thé J'adore Menthe",
    categorie: 'the',
    prix: 500,
    quantite: 200,
    seuilAlerte: 50,
    unite: 'boîtes',
    image: '/images/Thé.webp',
  },
  {
    id: 'p8',
    nom: "Thé J'adore Vert",
    categorie: 'the',
    prix: 450,
    quantite: 175,
    seuilAlerte: 50,
    unite: 'boîtes',
    image: '/images/Thé.webp',
  },
  {
    id: 'p9',
    nom: "Vinaigre J'adore 1L",
    categorie: 'vinaigre',
    prix: 800,
    quantite: 12,
    seuilAlerte: 30,
    unite: 'bouteilles',
    image: '/images/Vinaigre.jpeg',
  },
  {
    id: 'p10',
    nom: "Eau J'adore 1.5L",
    categorie: 'eau',
    prix: 300,
    quantite: 90,
    seuilAlerte: 20,
    unite: 'bouteilles',
    image: '/images/Eau.jpg',
  },
  {
    id: 'p11',
    nom: "Eau J'adore 5L",
    categorie: 'eau',
    prix: 600,
    quantite: 65,
    seuilAlerte: 20,
    unite: 'bidons',
    image: '/images/Eau.jpg',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    numero: 'CMD-2026-001',
    client: 'Boutique Sandaga',
    vendeurId: 'u3',
    vendeurNom: 'Ibrahima Sow',
    articles: [
      { produitId: 'p1', produitNom: "Huile J'adore 1L", quantite: 24, prixUnitaire: 1500 },
      { produitId: 'p5', produitNom: "Sucre J'adore 1kg", quantite: 10, prixUnitaire: 750 },
    ],
    montantTotal: 43500,
    statut: 'validee',
    canal: 'physique',
    modePaiement: 'especes',
    date: '2026-05-17T09:30:00Z',
  },
  {
    id: 'o2',
    numero: 'CMD-2026-002',
    client: 'Supermarché Dakar',
    vendeurId: 'u4',
    vendeurNom: 'Aissatou Fall',
    articles: [
      { produitId: 'p3', produitNom: "Riz J'adore 25kg", quantite: 5, prixUnitaire: 18000 },
      { produitId: 'p2', produitNom: "Huile J'adore 5L", quantite: 3, prixUnitaire: 6500 },
    ],
    montantTotal: 109500,
    statut: 'en_attente',
    canal: 'distance',
    modePaiement: 'wave',
    date: '2026-05-17T10:15:00Z',
  },
  {
    id: 'o3',
    numero: 'CMD-2026-003',
    client: 'Marché Tilène',
    vendeurId: 'u3',
    vendeurNom: 'Ibrahima Sow',
    articles: [
      { produitId: 'p7', produitNom: "Thé J'adore Menthe", quantite: 12, prixUnitaire: 500 },
      { produitId: 'p10', produitNom: "Eau J'adore 1.5L", quantite: 6, prixUnitaire: 300 },
    ],
    montantTotal: 7800,
    statut: 'validee',
    canal: 'physique',
    modePaiement: 'orange_money',
    date: '2026-05-16T14:00:00Z',
  },
  {
    id: 'o4',
    numero: 'CMD-2026-004',
    client: 'Chez Aminata',
    vendeurId: 'u4',
    vendeurNom: 'Aissatou Fall',
    articles: [
      { produitId: 'p6', produitNom: "Sucre J'adore 5kg", quantite: 2, prixUnitaire: 3500 },
    ],
    montantTotal: 7000,
    statut: 'annulee',
    canal: 'distance',
    modePaiement: 'virement',
    date: '2026-05-15T11:00:00Z',
  },
  {
    id: 'o5',
    numero: 'CMD-2026-005',
    client: 'Épicerie Liberté 6',
    vendeurId: 'u3',
    vendeurNom: 'Ibrahima Sow',
    articles: [
      { produitId: 'p1', produitNom: "Huile J'adore 1L", quantite: 48, prixUnitaire: 1500 },
      { produitId: 'p4', produitNom: "Riz J'adore 5kg", quantite: 10, prixUnitaire: 3800 },
    ],
    montantTotal: 110000,
    statut: 'validee',
    canal: 'physique',
    modePaiement: 'especes',
    date: '2026-05-14T08:45:00Z',
  },
];

export const MOCK_MOUVEMENTS: MouvementStock[] = [
  {
    id: 'm1',
    produitId: 'p1',
    produitNom: "Huile J'adore 1L",
    type: 'entree',
    quantite: 100,
    date: '2026-05-15T08:00:00Z',
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
    note: 'Livraison fournisseur',
  },
  {
    id: 'm2',
    produitId: 'p6',
    produitNom: "Sucre J'adore 5kg",
    type: 'reapprovisionnement',
    quantite: 50,
    date: '2026-05-16T10:30:00Z',
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
    note: 'Réappro urgent stock bas',
  },
  {
    id: 'm3',
    produitId: 'p3',
    produitNom: "Riz J'adore 25kg",
    type: 'sortie',
    quantite: 10,
    date: '2026-05-16T14:00:00Z',
    utilisateurId: 'u3',
    utilisateurNom: 'Ibrahima Sow',
    note: 'Vente CMD-2026-003',
  },
  {
    id: 'm4',
    produitId: 'p9',
    produitNom: "Vinaigre J'adore 1L",
    type: 'entree',
    quantite: 60,
    date: '2026-05-17T07:00:00Z',
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'a1',
    action: 'connexion',
    utilisateurId: 'u1',
    utilisateurNom: 'Mamadou Diallo',
    detail: 'Connexion administrateur',
    date: '2026-05-17T07:45:00Z',
  },
  {
    id: 'a2',
    action: 'vente_effectuee',
    utilisateurId: 'u3',
    utilisateurNom: 'Ibrahima Sow',
    detail: 'Vente CMD-2026-001 — 43 500 FCFA',
    date: '2026-05-17T09:30:00Z',
    orderId: 'o1',
  },
  {
    id: 'a3',
    action: 'entree_stock',
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
    detail: "Entrée 100 bouteilles Huile J'adore 1L",
    date: '2026-05-15T08:00:00Z',
    produitId: 'p1',
  },
  {
    id: 'a4',
    action: 'commande_validee',
    utilisateurId: 'u4',
    utilisateurNom: 'Aissatou Fall',
    detail: 'Commande CMD-2026-002 validée — 109 500 FCFA',
    date: '2026-05-17T10:15:00Z',
    orderId: 'o2',
  },
  {
    id: 'a5',
    action: 'modification_produit',
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
    detail: "Prix Huile J'adore 1L mis à jour : 1 400 → 1 500 FCFA",
    date: '2026-05-14T11:00:00Z',
    produitId: 'p1',
  },
  {
    id: 'a6',
    action: 'creation_utilisateur',
    utilisateurId: 'u1',
    utilisateurNom: 'Mamadou Diallo',
    detail: 'Création compte vendeur : Aissatou Fall',
    date: '2024-04-01T08:00:00Z',
  },
  {
    id: 'a7',
    action: 'commande_annulee',
    utilisateurId: 'u4',
    utilisateurNom: 'Aissatou Fall',
    detail: 'Commande CMD-2026-004 annulée — motif client',
    date: '2026-05-15T11:30:00Z',
    orderId: 'o4',
  },
  {
    id: 'a8',
    action: 'reapprovisionnement' as AuditAction,
    utilisateurId: 'u2',
    utilisateurNom: 'Fatou Ndiaye',
    detail: "Réapprovisionnement 50 sachets Sucre J'adore 5kg",
    date: '2026-05-16T10:30:00Z',
    produitId: 'p6',
  },
];

export const SALES_CHART_DATA = [
  { jour: 'Lun', ventes: 85000 },
  { jour: 'Mar', ventes: 120000 },
  { jour: 'Mer', ventes: 95000 },
  { jour: 'Jeu', ventes: 140000 },
  { jour: 'Ven', ventes: 175000 },
  { jour: 'Sam', ventes: 220000 },
  { jour: 'Dim', ventes: 60000 },
];
